version: "3"
services:
  infra:
    build: ./infra-service/.
    container_name: infra
    stop_signal: SIGINT
    depends_on:
      - infra_db
    ports:
      - "3000:3000"
    environment:
      FLASK_RUN_PORT: 3000
      DB_URL: http://infra_db:3306
  stats:
    build: ./stats-service/.
    container_name: stats
    stop_signal: SIGINT
    depends_on:
      - stats_db
    ports:
      - "5000:5000"
    environment:
      FLASK_RUN_PORT: 5000
      INFRA_URL: http://infra:3000/
      DB_URL: http://stats_db:3306
  geo:
    build: ./geo-service/.
    container_name: geo
    stop_signal: SIGINT
    depends_on:
      - geo_db
    ports:
      - "4000:4000"
    environment:
      FLASK_RUN_PORT: 4000
      INFRA_URL: http://infra:3000/
      DB_URL: http://geo_db:3306
  infra_db:
    container_name: infra_db
    image: mysql
    ports:
      - "81:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DATABASE=db
    volumes:
      - .//infra-service/infra_db_init_mysql.sql:/docker-entrypoint-initdb.d/init.sql
  geo_db:
    container_name: geo_db
    image: mysql
    ports:
      - "82:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DATABASE=db
    volumes:
      - .//geo-service/geo_db_init_mysql.sql:/docker-entrypoint-initdb.d/init.sql
  stats_db:
    container_name: stats_db
    image: mysql
    ports:
      - "83:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DATABASE=db
    volumes:
      - .//stats-service/stats_db_init_mysql.sql:/docker-entrypoint-initdb.d/init.sql
