apiVersion: apps/v1
kind: Deployment
metadata:
  name: geolocation-service-deployment
  labels:
    app: geo-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: geo-deploy
  template:
    metadata:
      labels:
        app: geo-deploy
    spec:
      containers:
        - name: geo-deploy
          image: resilientsixregistry.azurecr.io/geo-service:v2.0.3
          env:
            - name: FLASK_RUN_PORT
              value: "4000"
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "128Mi"
              cpu: "250m"
            requests:
              memory: "128Mi"
              cpu: "250m"
      #     volumeMounts:
      #       - name: secrets-store01-inline
      #         mountPath: "/mnt/secrets-store"
      #         readOnly: true
      # volumes:
      #   - name: secrets-store01-inline
      #     csi:
      #       driver: secrets-store.csi.k8s.io
      #       readOnly: true
      #       volumeAttributes:
      #         secretProviderClass: "keyvault-name"
---
apiVersion: v1
kind: Service
metadata:
  name: geo-service
spec:
  selector:
    app: geo-deploy
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: geo-service-public
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 4000
  selector:
    app: geo-deploy
