apiVersion: apps/v1
kind: Deployment
metadata:
  name: statistics-service-deployment
  labels:
    app: stats-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stats-deploy
  template:
    metadata:
      labels:
        app: stats-deploy
    spec:
      containers:
        - name: stats-deploy
          image: resilientsixregistry.azurecr.io/stats-service:v1.0.3
          env:
            - name: FLASK_RUN_PORT
              value: "5000"
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "128Mi"
              cpu: "250m"
            requests:
              memory: "128Mi"
              cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: stats-service
spec:
  selector:
    app: stats-deploy
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: stats-service-public
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 5000
  selector:
    app: stats-deploy
