version: "3"
services:
    db:
      container_name: db
      image: mysql
      ports:
       - "3306:3306"  
      environment:
         - MYSQL_ROOT_PASSWORD=mysql
         - MYSQL_DATABASE=db

      volumes:
        #  - /home/user/db/mysql/data:/var/lib/mysql
        #  - //home/user/db/mysql/init:geo_db_init_mysql.sql
         - .//geo_db_init_mysql.sql:/docker-entrypoint-initdb.d/init.sql


        #  - /home/user/db/mysql/data:/var/lib/mysql
        #  - /home/user/db/mysql/init:/docker-entrypoint-initdb.d/:ro