apiVersion: apps/v1
kind: Deployment
metadata:
  name: geolocation-service-deployment
  labels:
    app: geo-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: geo-deploy
  template:
    metadata:
      labels:
        app: geo-deploy
    spec:
      containers:
        - name: geo-deploy
          image: marcinziolkowski/geo-service:v1.0.1
          env:
            - name: FLASK_RUN_PORT
              value: "4000"
            - name: INFRA_URL
              value: infra-service
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "128Mi"
              cpu: "250m"
            requests:
              memory: "128Mi"
              cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: geo-service
spec:
  selector:
    app: geo-deploy
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 4000
