apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: infra-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: infrastructure-service-deployment
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 15