apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: stats-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: statistics-service-deployment
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50