apiVersion: apps/v1
kind: Deployment
metadata:
  name: statistics-service-deployment
  labels:
    app: stats-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: stats-deploy
  template:
    metadata:
      labels:
        app: stats-deploy
    spec:
      containers:
      - name: stats
        image: marcinziolkowski/stats-service:v1.0.1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: stats-service
spec:
  selector:
    app: stats-deploy
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
